/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as SavedIndexRouteImport } from './routes/saved/index'
import { Route as ResearchIndexRouteImport } from './routes/research/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as PapersIndexRouteImport } from './routes/papers/index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications/index'
import { Route as NewsletterIndexRouteImport } from './routes/newsletter/index'
import { Route as MembersIndexRouteImport } from './routes/members/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as ApplicationsIndexRouteImport } from './routes/applications/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SavedCollectionsRouteImport } from './routes/saved/collections'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as PapersSlugRouteImport } from './routes/papers/$slug'
import { Route as NewsletterSlugRouteImport } from './routes/newsletter/$slug'
import { Route as MembersIdRouteImport } from './routes/members/$id'
import { Route as LeadApplyRouteImport } from './routes/lead/apply'
import { Route as JobsTrackerRouteImport } from './routes/jobs/tracker'
import { Route as JobsSlugRouteImport } from './routes/jobs/$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as EventsSlugRouteImport } from './routes/events/$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AccountSecurityRouteImport } from './routes/account/security'
import { Route as AccountPreferencesRouteImport } from './routes/account/preferences'
import { Route as AccountNotificationsRouteImport } from './routes/account/notifications'
import { Route as ProjectsManageIndexRouteImport } from './routes/projects/manage/index'
import { Route as ProjectsManageSlugRouteImport } from './routes/projects/manage/$slug'
import { Route as ProjectsEditSlugRouteImport } from './routes/projects/edit/$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedIndexRoute = SavedIndexRouteImport.update({
  id: '/saved/',
  path: '/saved/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersIndexRoute = PapersIndexRouteImport.update({
  id: '/papers/',
  path: '/papers/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterIndexRoute = NewsletterIndexRouteImport.update({
  id: '/newsletter/',
  path: '/newsletter/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedCollectionsRoute = SavedCollectionsRouteImport.update({
  id: '/saved/collections',
  path: '/saved/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersSlugRoute = PapersSlugRouteImport.update({
  id: '/papers/$slug',
  path: '/papers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterSlugRoute = NewsletterSlugRouteImport.update({
  id: '/newsletter/$slug',
  path: '/newsletter/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIdRoute = MembersIdRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadApplyRoute = LeadApplyRouteImport.update({
  id: '/lead/apply',
  path: '/lead/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsTrackerRoute = JobsTrackerRouteImport.update({
  id: '/jobs/tracker',
  path: '/jobs/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsSlugRoute = JobsSlugRouteImport.update({
  id: '/jobs/$slug',
  path: '/jobs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/account/security',
  path: '/account/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPreferencesRoute = AccountPreferencesRouteImport.update({
  id: '/account/preferences',
  path: '/account/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/account/notifications',
  path: '/account/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsManageIndexRoute = ProjectsManageIndexRouteImport.update({
  id: '/projects/manage/',
  path: '/projects/manage/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsManageSlugRoute = ProjectsManageSlugRouteImport.update({
  id: '/projects/manage/$slug',
  path: '/projects/manage/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsEditSlugRoute = ProjectsEditSlugRouteImport.update({
  id: '/projects/edit/$slug',
  path: '/projects/edit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/security': typeof AccountSecurityRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/events/$slug': typeof EventsSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/jobs/tracker': typeof JobsTrackerRoute
  '/lead/apply': typeof LeadApplyRoute
  '/members/$id': typeof MembersIdRoute
  '/newsletter/$slug': typeof NewsletterSlugRoute
  '/papers/$slug': typeof PapersSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/new': typeof ProjectsNewRoute
  '/saved/collections': typeof SavedCollectionsRoute
  '/admin/': typeof AdminIndexRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/members/': typeof MembersIndexRoute
  '/newsletter/': typeof NewsletterIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/papers/': typeof PapersIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/saved/': typeof SavedIndexRoute
  '/search/': typeof SearchIndexRoute
  '/projects/edit/$slug': typeof ProjectsEditSlugRoute
  '/projects/manage/$slug': typeof ProjectsManageSlugRoute
  '/projects/manage/': typeof ProjectsManageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/security': typeof AccountSecurityRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/events/$slug': typeof EventsSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/jobs/tracker': typeof JobsTrackerRoute
  '/lead/apply': typeof LeadApplyRoute
  '/members/$id': typeof MembersIdRoute
  '/newsletter/$slug': typeof NewsletterSlugRoute
  '/papers/$slug': typeof PapersSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/new': typeof ProjectsNewRoute
  '/saved/collections': typeof SavedCollectionsRoute
  '/admin': typeof AdminIndexRoute
  '/applications': typeof ApplicationsIndexRoute
  '/events': typeof EventsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/members': typeof MembersIndexRoute
  '/newsletter': typeof NewsletterIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/papers': typeof PapersIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/research': typeof ResearchIndexRoute
  '/saved': typeof SavedIndexRoute
  '/search': typeof SearchIndexRoute
  '/projects/edit/$slug': typeof ProjectsEditSlugRoute
  '/projects/manage/$slug': typeof ProjectsManageSlugRoute
  '/projects/manage': typeof ProjectsManageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/security': typeof AccountSecurityRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/events/$slug': typeof EventsSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/jobs/tracker': typeof JobsTrackerRoute
  '/lead/apply': typeof LeadApplyRoute
  '/members/$id': typeof MembersIdRoute
  '/newsletter/$slug': typeof NewsletterSlugRoute
  '/papers/$slug': typeof PapersSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/new': typeof ProjectsNewRoute
  '/saved/collections': typeof SavedCollectionsRoute
  '/admin/': typeof AdminIndexRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/members/': typeof MembersIndexRoute
  '/newsletter/': typeof NewsletterIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/papers/': typeof PapersIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/saved/': typeof SavedIndexRoute
  '/search/': typeof SearchIndexRoute
  '/projects/edit/$slug': typeof ProjectsEditSlugRoute
  '/projects/manage/$slug': typeof ProjectsManageSlugRoute
  '/projects/manage/': typeof ProjectsManageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/account/notifications'
    | '/account/preferences'
    | '/account/security'
    | '/auth/callback'
    | '/events/$slug'
    | '/guides/$slug'
    | '/jobs/$slug'
    | '/jobs/tracker'
    | '/lead/apply'
    | '/members/$id'
    | '/newsletter/$slug'
    | '/papers/$slug'
    | '/projects/$slug'
    | '/projects/new'
    | '/saved/collections'
    | '/admin/'
    | '/applications/'
    | '/events/'
    | '/guides/'
    | '/jobs/'
    | '/members/'
    | '/newsletter/'
    | '/notifications/'
    | '/papers/'
    | '/projects/'
    | '/research/'
    | '/saved/'
    | '/search/'
    | '/projects/edit/$slug'
    | '/projects/manage/$slug'
    | '/projects/manage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/account/notifications'
    | '/account/preferences'
    | '/account/security'
    | '/auth/callback'
    | '/events/$slug'
    | '/guides/$slug'
    | '/jobs/$slug'
    | '/jobs/tracker'
    | '/lead/apply'
    | '/members/$id'
    | '/newsletter/$slug'
    | '/papers/$slug'
    | '/projects/$slug'
    | '/projects/new'
    | '/saved/collections'
    | '/admin'
    | '/applications'
    | '/events'
    | '/guides'
    | '/jobs'
    | '/members'
    | '/newsletter'
    | '/notifications'
    | '/papers'
    | '/projects'
    | '/research'
    | '/saved'
    | '/search'
    | '/projects/edit/$slug'
    | '/projects/manage/$slug'
    | '/projects/manage'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/account/notifications'
    | '/account/preferences'
    | '/account/security'
    | '/auth/callback'
    | '/events/$slug'
    | '/guides/$slug'
    | '/jobs/$slug'
    | '/jobs/tracker'
    | '/lead/apply'
    | '/members/$id'
    | '/newsletter/$slug'
    | '/papers/$slug'
    | '/projects/$slug'
    | '/projects/new'
    | '/saved/collections'
    | '/admin/'
    | '/applications/'
    | '/events/'
    | '/guides/'
    | '/jobs/'
    | '/members/'
    | '/newsletter/'
    | '/notifications/'
    | '/papers/'
    | '/projects/'
    | '/research/'
    | '/saved/'
    | '/search/'
    | '/projects/edit/$slug'
    | '/projects/manage/$slug'
    | '/projects/manage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountPreferencesRoute: typeof AccountPreferencesRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  EventsSlugRoute: typeof EventsSlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  JobsSlugRoute: typeof JobsSlugRoute
  JobsTrackerRoute: typeof JobsTrackerRoute
  LeadApplyRoute: typeof LeadApplyRoute
  MembersIdRoute: typeof MembersIdRoute
  NewsletterSlugRoute: typeof NewsletterSlugRoute
  PapersSlugRoute: typeof PapersSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  SavedCollectionsRoute: typeof SavedCollectionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  MembersIndexRoute: typeof MembersIndexRoute
  NewsletterIndexRoute: typeof NewsletterIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  PapersIndexRoute: typeof PapersIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ResearchIndexRoute: typeof ResearchIndexRoute
  SavedIndexRoute: typeof SavedIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  ProjectsEditSlugRoute: typeof ProjectsEditSlugRoute
  ProjectsManageSlugRoute: typeof ProjectsManageSlugRoute
  ProjectsManageIndexRoute: typeof ProjectsManageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved/': {
      id: '/saved/'
      path: '/saved'
      fullPath: '/saved/'
      preLoaderRoute: typeof SavedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/': {
      id: '/research/'
      path: '/research'
      fullPath: '/research/'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/': {
      id: '/papers/'
      path: '/papers'
      fullPath: '/papers/'
      preLoaderRoute: typeof PapersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/': {
      id: '/newsletter/'
      path: '/newsletter'
      fullPath: '/newsletter/'
      preLoaderRoute: typeof NewsletterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/': {
      id: '/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved/collections': {
      id: '/saved/collections'
      path: '/saved/collections'
      fullPath: '/saved/collections'
      preLoaderRoute: typeof SavedCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/$slug': {
      id: '/papers/$slug'
      path: '/papers/$slug'
      fullPath: '/papers/$slug'
      preLoaderRoute: typeof PapersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/$slug': {
      id: '/newsletter/$slug'
      path: '/newsletter/$slug'
      fullPath: '/newsletter/$slug'
      preLoaderRoute: typeof NewsletterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$id': {
      id: '/members/$id'
      path: '/members/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof MembersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead/apply': {
      id: '/lead/apply'
      path: '/lead/apply'
      fullPath: '/lead/apply'
      preLoaderRoute: typeof LeadApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/tracker': {
      id: '/jobs/tracker'
      path: '/jobs/tracker'
      fullPath: '/jobs/tracker'
      preLoaderRoute: typeof JobsTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$slug': {
      id: '/jobs/$slug'
      path: '/jobs/$slug'
      fullPath: '/jobs/$slug'
      preLoaderRoute: typeof JobsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/security': {
      id: '/account/security'
      path: '/account/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/preferences': {
      id: '/account/preferences'
      path: '/account/preferences'
      fullPath: '/account/preferences'
      preLoaderRoute: typeof AccountPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/account/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/manage/': {
      id: '/projects/manage/'
      path: '/projects/manage'
      fullPath: '/projects/manage/'
      preLoaderRoute: typeof ProjectsManageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/manage/$slug': {
      id: '/projects/manage/$slug'
      path: '/projects/manage/$slug'
      fullPath: '/projects/manage/$slug'
      preLoaderRoute: typeof ProjectsManageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/edit/$slug': {
      id: '/projects/edit/$slug'
      path: '/projects/edit/$slug'
      fullPath: '/projects/edit/$slug'
      preLoaderRoute: typeof ProjectsEditSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountPreferencesRoute: AccountPreferencesRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  EventsSlugRoute: EventsSlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  JobsSlugRoute: JobsSlugRoute,
  JobsTrackerRoute: JobsTrackerRoute,
  LeadApplyRoute: LeadApplyRoute,
  MembersIdRoute: MembersIdRoute,
  NewsletterSlugRoute: NewsletterSlugRoute,
  PapersSlugRoute: PapersSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  SavedCollectionsRoute: SavedCollectionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  MembersIndexRoute: MembersIndexRoute,
  NewsletterIndexRoute: NewsletterIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  PapersIndexRoute: PapersIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ResearchIndexRoute: ResearchIndexRoute,
  SavedIndexRoute: SavedIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  ProjectsEditSlugRoute: ProjectsEditSlugRoute,
  ProjectsManageSlugRoute: ProjectsManageSlugRoute,
  ProjectsManageIndexRoute: ProjectsManageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
